<span className="supplier-box">
        <h2>Products In-Out</h2>
        <div className="supplier-content-box">
          <p>Recent</p>
          <div className="supplier-content-input-box">
            <div className="supplier-content-input-left">
              <input type="text" />
              {/* <img src={searchWhiteIcon} alt="" height="20px" /> */}
            </div>
            <div className="supplier-content-input-right">
              <select
                name=""
                id=""
                className="supplier-content-input-right-filters"
              >
                <option value="" selected>
                  Category
                </option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
              </select>
              <select
                name=""
                id=""
                className="supplier-content-input-right-filters"
              >
                <option selected>Stock Status</option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
              </select>
              <button className="supplier-content-input-right-filters">
                Export List
              </button>
            </div>
          </div>
          <table style={{ textAlign: "left" }}>
            <tr>
              <th>Product ID</th>
              <th>Category</th>
              <th>Item</th>
              <th>Added on</th>
              <th>Amount</th>
              <th>Order Status</th>
              <th>Quantity</th>
              <th>Details</th>
            </tr>
            <tr>
              <td>1234586</td>
              <td>Electronics</td>
              <td>Nike men's air shoes</td>
              <td>12-aug-2022||16:00</td>
              <td>9995</td>
              <td>In Stock</td>
              <td>10</td>
              <td>
                <a href="">view details</a>
              </td>
            </tr>
            <tr>
              <td>1234586</td>
              <td>Electronics</td>
              <td>Nike men's air shoes</td>
              <td>12-aug-2022||16:00</td>
              <td>9995</td>
              <td>In Stock</td>
              <td>10</td>
              <td>
                <a href="">view details</a>
              </td>
            </tr>
            <tr>
              <td>1234586</td>
              <td>Electronics</td>
              <td>Nike men's air shoes</td>
              <td>12-aug-2022||16:00</td>
              <td>9995</td>
              <td>In Stock</td>
              <td>10</td>
              <td>
                <a href="">view details</a>
              </td>
            </tr>
            <tr>
              <td>1234586</td>
              <td>Electronics</td>
              <td>Nike men's air shoes</td>
              <td>12-aug-2022||16:00</td>
              <td>9995</td>
              <td>In Stock</td>
              <td>10</td>
              <td>
                <a href="">view details</a>
              </td>
            </tr>
            <tr>
              <td>1234586</td>
              <td>Electronics</td>
              <td>Nike men's air shoes</td>
              <td>12-aug-2022||16:00</td>
              <td>9995</td>
              <td>In Stock</td>
              <td>10</td>
              <td>
                <a href="">view details</a>
              </td>
            </tr>
            <tr>
              <td>1234586</td>
              <td>Electronics</td>
              <td>Nike men's air shoes</td>
              <td>12-aug-2022||16:00</td>
              <td>9995</td>
              <td>In Stock</td>
              <td>10</td>
              <td>
                <a href="">view details</a>
              </td>
            </tr>
          </table>
        </div>
      </span>